export type FieldType = {
  name?: string;
  password?: string;
  remember?: string;
  email?: string;
  empresa?: string;
  telefono?: number;
  cargo?: string;
  pais?: string;
  yeguada?: string;
  salida?: number;
  habitacion?: string;
  adicional?: string;
  comida?: string;
  taller?: string;
  boleto?: string;
  FechaNacimiento?: number;
  getFullyear?: number;
  confirmPassword?: number;
  checkbox?: string;
  provincia?: string;
  otraHabita?: string;
  otraComida?: string;
  otroCargo?: string;
};
